### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by piernik** [ThumbsAlmighty/amCharts-Angular#2]
Great would be to give us config to define globals like colors, credit position, width, height and so on - would be great.

**Comment by GrantMStevens** [comment]
You can do all of that. If you look at the source, I have exposed a lot of those properties via the 'options' attribute on the directive. You can create an object on your scope, like:

```
$scope.amChartOptions = {
    data: $scope.myDataObject,
    lineColor: '#000000',
    marginLeft: '40'
}
```

then pass it to your directive

```
<am-chart id="myFirstChart" options="amChartOptions" height="300px" width="500px"></am-chart>
```

Again, I'm still working on exposing a lot more and trying to come with conventions for properly handling things like live chart update.

**Comment by piernik** [comment]
Yes, but You have to define it every time You use Your directive.
Better would be global config.

**Comment by GrantMStevens** [comment]
That's the point. Directives are compartmentalized so they can be ultra reusable. I would not want to pollute some kind of global scope with a config for these charts. Instead, I could store that config object in a more persistent location, like a service, and retrieve it and modify it as I need it. In all but the rarest of use cases, you're going to have a different dataset and probably different key and value fields for the graph(s) in each chart.

The more you try to make a directive like this specific to your use case, the more you couple it to your application. I wrote this to be application agnostic so that anyone can just grab the directive, throw it in their project, and be up and running without having to worry about some of the finer details.
