### ISSUE TITLE
Does not work in Bootstrap's tabs directive

### ISSUE THREAD

**Issue by mkavrukova** [ThumbsAlmighty/amCharts-Angular#24]

**Comment by GrantMStevens** [comment]
Are you sure this is not just a scoping issue? Are you using controller-as syntax? If I remember correctly, a lot of the ui-boostrap directives create an isolate scope, so if you're trying to reference a scope variable for your config object to pass in to the AmCharts directive, the $scope variable in the view could be referencing that isolate scope from the ui-boostrap tab instead of the parent scope you think you're referencing. This is more than likely your problem.

If it isnt, create a fiddle please.
