### ISSUE TITLE
Radar chart:  chart.addChartCursor is not a function

### ISSUE THREAD

**Issue by florissmit10** [ThumbsAlmighty/amCharts-Angular#31]
I'm trying to get a RadarChart to work througth this directive, but im getting the error: chart.addChartCursor is not a function

http://jsfiddle.net/w3vpc35o/119/
Am i configuring this thing wrong? It did work without angular and amCharts 3.17.

**Comment by GrantMStevens** [comment]
This directive only supports a portion of the AmCharts library, since the API is rather large. Radar charts are not one of the types of charts I built in to it because they have a different configuration and would require conditional branching to support. I can add it to the list of things to add when I find the time though.
