### ISSUE TITLE
Is it possible to use a theme? (light, chalk, etc)

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [ThumbsAlmighty/amCharts-Angular#7]
Hi, this is a great directive! Everything works great except by the fact that it is not respecting the theme I choose... even the default light theme has weird colors like orange and green! Maybe I'm doing something wrong?

Thanks!

**Comment by GrantMStevens** [comment]
I've spent the past couple of hours playing with this, and it looks like a bug with the AmCharts javascript api.

According to the AmCharts documentation, you should be able to simply supply the theme as a string value in the object you pass in to create the chart. They provide examples using the AmCharts.MakeChart() function, but I am using the javascript api to provide a more robust and dynamic implementation.

One possible workaround for now is to set your themes globally. You can do so like this:
`AmCharts.theme = AmCharts.themes.light;`

Make sure you have included the theme js file that AmCharts supplies in order to use the theme you're calling.

I'm going to reach out to the AmCharts team to see if they can provide any input or open a ticket, but I have had no luck getting a response to any of the issues I have raised with them. I'll report back if I find out more.

**Comment by DanielFerreiraJorge** [comment]
Hi thank you i will try this workaround! If it works it will be enough for me... and just so you know, i do not think the problem is the amcharts api, because if I hard code the same javascript in my controller, without using the directive, the theme works perfectly... 

Thank you very much for your answer!

**Comment by GrantMStevens** [comment]
I tested the js api outside of my directive and it is the problem. Keep in mind, when I refer to the JavaScript api in AmCharts, I'm not referencing the MakeChart() function, which does work with themes.

**Comment by mg1075** [comment]
Is there a codepen, fiddle, jsbin or anything to show the problem?

**Comment by GrantMStevens** [comment]
I got a reply back from the AmCharts team. Apparently, using something like:

``` javascript
var chart = new AmCharts.AmSerialChart();
chart.theme = 'light';
```

doesnt work, because the theme needs to be applied when AmSerialChart is instantiated. I'll have to add logic in to do something like:

`var chart = new AmCharts.AmSerialChart(AmCharts.themes[themeName]);`

It should be a quick fix, so I'll do that when I get a chance this weekend.

**Comment by GrantMStevens** [comment]
Added support for functionality in d0fea0cdd4f475a6256ddfdc22db581c45d71af0

**Comment by ilan-senexx** [comment]
Hi @GrantMStevens , thank you for this great directive.
 it seems that:
AmCharts.themes  = Object {}
so i cant choose any theme. did you test it? 

many thanks

**Comment by GrantMStevens** [comment]
Themes are javascript objects, not strings. Reference the AmCharts documentation for themes here: http://www.amcharts.com/tutorials/working-with-themes/

The way you use them is to define a theme property on the options object you pass in to the directive. This should be a string value for the name of the theme you want you use. I am using square bracket notation to take that string and call it as a property on the AmCharts.themes object like I showed in my comment earlier in this thread.

You have to reference the theme's js file in order to be able to include it. Here is an updated jsfiddle that references 4 theme files and shows how to use the theme property: http://jsfiddle.net/w3vpc35o/29/
